config/routes.rb
Rails.application.routes.draw do
  root to: "boats#index"
  devise_for :users, controllers: {
     sessions: 'users/sessions',
     omniauth_callbacks: 'users/omniauth_callbacks'
   }

   devise_scope :user do
    get '/users/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2', as: 'user_google_oauth2_omniauth_callback'
  end

  get 'boats/map_view', to: 'boats#map_view', as: 'boats_map_view'

  resources :users do
    member do
      get 'my_boats', to: 'boats#my_boats'
      get 'my_bookings', to: 'bookings#my_bookings'
    end
  end

  resources :boats do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:index]
  end

  resources :bookings, only: [:index, :show, :destroy, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat
  has_many :reviews, dependent: :destroy


  validates :user, presence: true
  validates :boat, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]
  def index
    @bookings = policy_scope(Booking).all
    @future_bookings = Booking.where('start_date >= ?', Date.today).order(start_date: :asc)
    @past_bookings = Booking.where('start_date < ?', Date.today).order(start_date: :asc)

    @bookings = @future_bookings + @past_bookings
  end

  def show
    authorize @booking
    @booking = Booking.find(params[:id])
    @boat = @booking.boat
  end

  # def my_bookings
  #   @user = User.find(params[:id])
  #   @bookings = @user.bookings
  #   @boats = policy_scope(Booking).all
  # end

  # /boats/:boat_id/bookings
  def new
    @booking = Booking.new
    @boat = Boat.find(params[:boat_id])
    authorize @booking
  end

  # /boats/:boat_id/bookings
  def create
    @booking = Booking.new(booking_params)
    @boat = Boat.find(params[:boat_id])
    @booking.boat = @boat
    @booking.user = current_user

    authorize @booking

    if @booking.save
      BookingNotificationMailer.booking_notification(@booking).deliver_now
      redirect_to bookings_path
    else
      render :new
    end
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end
  def booking_params
    params.require(:booking).permit(:content, :start_date, :end_date)
  end

end

app/views/bookings/edit.html.erb
<div class="container1" style="background-image: url('https://images.unsplash.com/photo-1468413253725-0d5181091126?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80')">
  <div class="container">
    <h2><strong>Edit Your Booking</strong></h2>
  </div>
    <div class="container2">
      <div class="form-container">
          <%# /boats/:boat_id/bookings %>
          <%= simple_form_for [@boat, @booking], html: { class: 'form' } do |f| %>
            <div class="form-group">
              <%= f.label :content %>
              <%= f.text_area :content, class: 'form-control' %>
            </div>

            <div class="form-group">
              <% f.label :start_date %>
              <%= f.input :start_date, as: :date, class: 'form-control' %>
            </div>

            <div class="form-group">
              <% f.label :end_date %>
              <%= f.input :end_date, as: :date, class: 'form-control' %>
            </div>
            <%= f.button :submit, class: 'btn submit-btn' %>
          <% end %>
      </div>

    </div>

</div>

app/views/bookings/index.html.erb
<h1 class="booking-header"> Your Bookings</h1>
<div class="container">
  <% @bookings.each do |booking| %>
    <%= link_to booking_path(booking.id), class: "link-to-btn" do %>
        <%= render partial: "shared/booking-card", locals: { booking: booking } %>
    <% end %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container1" style="background-image: url('https://images.unsplash.com/photo-1468413253725-0d5181091126?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80')">

    <div class="container">
      <h2><strong>Get your vacation started now...</strong></h2>
    </div>
      <div class="container2"> 
        <div class="form-container">
          <%= simple_form_for [@boat, @booking], html: { class: 'form' } do |f| %>
            <div class="form-group">
              <%= f.label :content %>
              <%= f.text_area :content, class: 'form-control' %>
            </div>

            <div class="form-group">
              <% f.label :start_date %>
              <%= f.input :start_date, as: :date, class: 'form-control' %>
            </div>

            <div class="form-group">
              <% f.label :end_date %>
              <%= f.input :end_date, as: :date, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.button :submit, class: 'btn submit-btn' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="booking-show">
    <%= render partial: "shared/booking-card", locals: { booking: @booking } %>
  </div>

  <div class="booking-show-btns">
      <% if policy(@booking).edit? %>
        <%= link_to "Edit", edit_booking_path(@booking), class: "btn show-btn" %>
      <% end %>

      <% if policy(@booking).destroy? %>
        <%= button_to "Delete", booking_path(@booking), class: "btn show-btn", method: :delete, data: { confirm: "Are you sure you want to delete this booking?" } %>
      <% end %>

      <%= link_to "Add Review", new_booking_review_path(@booking), class: "btn show-btn" %>
  </div>
</div>