config/routes.rb
Rails.application.routes.draw do
  root to: "boats#index"
  devise_for :users, controllers: {
     sessions: 'users/sessions',
     omniauth_callbacks: 'users/omniauth_callbacks'
   }

   devise_scope :user do
    get '/users/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2', as: 'user_google_oauth2_omniauth_callback'
  end

  get 'boats/map_view', to: 'boats#map_view', as: 'boats_map_view'

  resources :users do
    member do
      get 'my_boats', to: 'boats#my_boats'
      get 'my_bookings', to: 'bookings#my_bookings'
    end
  end

  resources :boats do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:index]
  end

  resources :bookings, only: [:index, :show, :destroy, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
end

app/views/shared/_boatcard.html.erb
<div class="card h-100 border-0 shadow-none w-100">
  <div class="rounded-img">
    <% if boat.photo.attached? %>
      <a href="<%= boat_path(boat) %>" class="text-decoration-none">
        <%= cl_image_tag boat.photo.key, transformation: { width: 300, height: 250, crop: :fill }, class: "img-fluid boat-image" %>
      </a>
    <% else %>
      <p>No photo available</p>
    <% end %>
  </div>
  <div class="card-body">
    <p class="card-title"><%= boat.name %></p>
    <div class="d-flex justify-content-between align-items-center">
      <p class="card-text"><%= boat.location %></p>
      <p class="card-text price-text">$<%= boat.price.to_i %>/day</p>
    </div>
  </div>
</div>


<%#
	<div class="row">
		<div class="col-md-4 col-sm-6 col-xs-12">
			<div class="card">
				<div class="cover item-a">
					<h1>Little<br>Bonsai</h1>
					<span class="price">$79</span>
					<div class="card-back">
						<a href="#">Add to cart</a>
						<a href="#">View detail</a>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-4 col-sm-6 col-xs-12">
			<div class="card">
				<div class="cover item-b">
					<h1>Tropical<br>Leaf</h1>
					<span class="price">$35</span>
					<div class="card-back">
						<a href="#">Add to cart</a>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-4 col-sm-6 col-xs-12">
			<div class="card">
				<div class="cover item-c">
					<h1>Marijuana<br>Chill</h1>
					<span class="price">$155</span>
					<div class="card-back">
						<a href="#">Add to cart</a>
					</div>
				</div>
			</div>
		</div>
	</div>
 %>

app/views/shared/_booking-card.html.erb
<div class="booking-card <%= booking.start_date >= Date.today ? 'future-booking' : 'past-booking' %>">
  <p class="booking-title"><%= booking.boat.name %></p>
  <div class="rounded-img">
    <div>
      <% if booking.boat.photo.attached? %>
        <%= cl_image_tag booking.boat.photo.key, transformation: { width: 300, height: 250, crop: :fill }, class: "img-fluid boat-image" %>
      <% else %>
        <p>No photo available</p>
      <% end %>
    </div>
  </div>

  <div class="content-container">
    <div class="content-between">
      <p class="booking-text"><%= booking.boat.location %></p>
      <p class="booking-price">$<%= booking.boat.price.to_i %>/day</p>
    </div>

    <div>
      <p class="booking-text"> <%= booking.content %> </p>
      <p class="booking-date">Check-in: <%= booking.start_date %></p>
      <p class="booking-date">Check-out: <%= booking.end_date %></p>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer container">
  <div class="footer-links">
    <a href="#" class="flexlink"><i class="fa-solid fa-location-dot fa-1x"></i>Destinations</a>
    <a href="#" class="flexlink"><i class="fa-solid fa-lock fa-1x"></i> Privacy</a>
    <a href="#" class="flexlink"><i class="fa-solid fa-info fa-1x"></i> Company</a>
    <a href="#" class="flexlink"><i class="fa-solid fa-earth-europe fa-1x"></i> Sitemap</a>
  </div>
  <div class="footer-copyright">
    &copy; 2023 Boatbnb, Inc.
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar-boatbnb this-container">
  <%= link_to root_path, style: 'text-decoration: none;' do %>
    <div class="boat-logo">
      <i class="fa-solid fa-sailboat boat-logo"></i>
      <p class="fa-solid boat-logo">BoatB&B</p>
    </div>
  <% end %>
  <div class="nav-link">
    <% if user_signed_in? %>
      <%= link_to "Create Listing", new_boat_path %>
      <%= link_to "My Boats", my_boats_user_path(current_user) %>
      <%= link_to "My Bookings", bookings_path %>
      <%= link_to "Log out  ", destroy_user_session_path, data: { turbo_method: :delete } %>
    <% else  %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>
</nav>

app/views/shared/_search_bar.html.erb
<form class="search-form" action="/boats" accept-charset="UTF-8" method="get">
  <div class="input-fields">
    <div>
      <input type="text" name="location" id="location" placeholder="Search city" class="location-input input">
    </div>
    <div>
      <input type="text" name="checkin_date" id="check-in_date" placeholder="Check In Date" class="date-input input" data-controller="flatpickr" readonly="readonly">
    </div>
    <div>
      <input type="text" name="checkout_date" id="check-out_date" placeholder="Check Out Date"  class="date-input input" data-controller="flatpickr" readonly="readonly">
    </div>
  </div>
  <button type="submit" name="commit" class="search-button" data-action="click->flatpickr#search" data-disable-with="Searching...">
  <i class="fa fa-search"></i> Search
  </button>
</form>

app/views/shared/_topsection_banner.erb
<header id="background-img">
  <div class="header this-container">
    <div class="search-bar">
      <%= render partial: "shared/search_bar", locals: { location: @locations } %>
    </div>
    <div class="text">
      <p>Number 1 Source for Boat Rentals</p>
    </div>
  </div>
</header>