config/routes.rb
Rails.application.routes.draw do
  root to: "boats#index"
  devise_for :users, controllers: {
     sessions: 'users/sessions',
     omniauth_callbacks: 'users/omniauth_callbacks'
   }

   devise_scope :user do
    get '/users/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2', as: 'user_google_oauth2_omniauth_callback'
  end

  get 'boats/map_view', to: 'boats#map_view', as: 'boats_map_view'

  resources :users do
    member do
      get 'my_boats', to: 'boats#my_boats'
      get 'my_bookings', to: 'bookings#my_bookings'
    end
  end

  resources :boats do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:index]
  end

  resources :bookings, only: [:index, :show, :destroy, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo

  validates :name, presence: true
  validates :user, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  # will need to add authentication for all except :index. :show
  skip_before_action :authenticate_user!, only: %i[index show map_view]
  before_action :set_boat, only: %i[show edit update destroy]

  def index
    @boats = policy_scope(Boat).all
    @markers = @boats.geocoded.map do |boat|
      {
        lat: boat.latitude,
        lng: boat.longitude,
        boatId: boat.id,
        info_window: render_to_string(partial: "popup", locals: { boat: boat }),
        image_url: helpers.asset_url("pin2.png")
      }
    end
    @locations = Boat.pluck(:location).uniq
    @boats = apply_search_filters(@boats, params)
    return unless params[:location].present?

    search_terms = params[:location].split
    search_query = search_terms.map { "location ILIKE ?" }.join(" AND ")
    @boats = @boats.where(search_query, *search_terms.map { |term| "%#{term}%" })
  end

  def map_view
    authorize Boat
    @boats = policy_scope(Boat).all
    @markers = @boats.geocoded.map do |boat|
      {
        lat: boat.latitude,
        lng: boat.longitude,
        boatId: boat.id,
        info_window: render_to_string(partial: "popup", locals: { boat: boat }),
        image_url: helpers.asset_url("pin2.png")
      }
    end
    @locations = Boat.pluck(:location).uniq
    @boats = apply_search_filters(@boats, params)
    return unless params[:location].present?

    search_terms = params[:location].split
    search_query = search_terms.map { "location ILIKE ?" }.join(" AND ")
    @boats = @boats.where(search_query, *search_terms.map { |term| "%#{term}%" })
    render 'map'
  end

  def show
    authorize @boat

    @markers = @boat.geocode.map {
      {
        lat: @boat.latitude,
        lng: @boat.longitude,
        info_window: render_to_string(partial: "popup", locals: { boat: @boat }),
        image_url: helpers.asset_url("pin2.png")
      }
    }
  end

  def my_boats
    @user = User.find(params[:id])
    @boats = @user.boats
    authorize @boats
  end

  def new
    @boat = Boat.new
    authorize @boat
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user = current_user
    authorize @boat
    if @boat.save
      redirect_to boat_path(@boat)
    else
      render :new
    end
  end

  def edit
    authorize @boat
  end

  def update
    authorize @boat
    @boat.update(boat_params)
    redirect_to boat_path(@boat)
  end

  def destroy
    authorize @boat
    @boat.user = current_user
    @boat.destroy

    redirect_to my_boats_user_path(@boat.user)
  end

  private

  def set_boat
    @boat = Boat.find(params[:id])
  end

  def boat_params
    params.require(:boat).permit(:name, :price, :description, :location, :photo)
  end

  def apply_search_filters(boats, params)
    location_query = params[:location].to_s.split.map(&:capitalize).join(' ')

    boats = boats.search_by_city(params[:search]) if params[:search].present?
    boats = boats.where("location ILIKE ?", "%#{location_query}%") if location_query.present?
    boats = boats.where(availability: true) if params[:availability].present?
    boats
  end
end

app/views/boats/_popup.html.erb
  <h3>Rating:<%= boat.rating %></h3>
  <p><%= boat.description.first(100) %>...</p>

app/views/boats/edit.html.erb
<main class="container1" style="background-image: url('https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80')">
    <div class="container text-center">
        <h2 id="edit-header">Edit Your Boat</h2>
    </div>
    <div class="edit-card">
        <div class="form-container">
            <%= simple_form_for @boat, html: { class: 'form-horizontal' } do |f| %>
              <div class="form-group">
                  <%= f.input :name, required: true, class: 'form-control' %>
              </div>
              <div class="form-group">
                  <%= f.input :description, required: true, class: 'form-control' %>
              </div>
              <div class="form-group">
                  <%= f.input :location, required: true, class: 'form-control' %>
              </div>
              <div class="form-group">
                  <%= f.input :price, required: true, class: 'form-control' %>
              </div>
              <div class="form-group">
                  <%= f.button :submit, class: 'btn submit-btn' %>
              </div>
            <% end %>
        </div>
    </div>

</main>

app/views/boats/index.html.erb
<%# <%= render partial: "shared/topsection_banner" %>
<%# <div class="bottom-section"> %>
  <%# <div class="cards">
    <% if params[:location].present? %>
      <%# <h1>Boats in <%= params[:location].capitalize %>
    <%# <% end %>
    <%# <% if @boats.empty? %>
      <%# <p>Sorry, no boats match your search criteria.</p>
    <% else %>
      <%# <div class="card-grid">
        <% @boats.each do |boat| %>
          <%# <div class="card-item"> %>

              <%# <%= render partial: "shared/boatcard", locals: { boat: boat } %>
            <%# </a> %>
          <%# </div> %>
        <%# <% end %>
      <%# </div> %>
    <%# <% end %>
  <%# </div> %>
  <%# <div class="map-container"> %>
    <%# <a href="/boats/map_view" class="btn btn-dark fixed-bottom btn-map">Map</a> %>
    <%# <% if @markers.present? %>
    <%# <div class="d-none d-sm-block col-sm-4"> %>
    <%# <div class="sticky-top sticky-bottom"> %>

    <%# </div> %>
    <%# <% end %>
  <%# </div>
</div> %>

<%= render partial: "shared/topsection_banner" %>
<main>
  <div class="main-index">
    <div class="card-grid" id="gridjs">
      <% @boats.each do |boat| %>
        <%= render partial: "shared/boatcard", locals: { boat: boat } %>
      <% end %>
    </div>
    <div class="map-container" id="mapjs">
      <div class="sticky-top sticky-bottom">
        <div data-controller="map" id="map" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" data-map-markers-value="<%= @markers.to_json %>" style="width: 100%" class="vh-100"></div>
      </div>
    </div>
    <button id="btn" data-controller="btn" class="btn btn-dark fixed-bottom btn-map">Map</button>
  </div>
</main>

app/views/boats/map_view.html.erb
<main class="main-container">
  <%= render partial: "shared/topsection_banner" %>
  <% if @markers.present? %>
    <!-- Show the map on screens above 425px -->
    <div class="col-12">
      <div class="sticky-top sticky-bottom">
        <div data-controller="map" id="map" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" data-map-markers-value="<%= @markers.to_json %>" style="width: 100%" class="vh-100"></div>
      </div>
    </div>
  <% end %>
</main>

app/views/boats/my_boats.html.erb
<main class="container text-center">
  <h1>My Listed Boats</h1>
</div>
<div class="container-fluid ">
  <div class="row row-cols-1 row-cols-md-4 justify-content-center">
    <% @boats.each do |boat| %>
      <div class="col mb-2">
        <a href="<%= boat_path(boat) %>" class="text-decoration-none">
          <%= render partial: "shared/boatcard", locals: { boat: boat } %>
        </a>
      </div>
    <% end %>
  </div>
</main>

app/views/boats/new.html.erb
<main class="main-container">
  <div id="background-image-boat">
    <div class="dark-overlay"></div>
      <div class="login-wrapper">
        <h2 id="listing-header">Create a New Listing</h2>
        <div class="log-in-card">
          <%= simple_form_for @boat, { class: "form-horizontal" } do |f| %>
            <div class="form-inputs">
              <%= f.input :price, label: "Price", required: true, class: "form-control" %>
              <%= f.input :description, label: "Description", required: true, class: "form-control" %>
              <%= f.input :location, label: "Location", required: true, class: "form-control" %>
              <%= f.input :photo, as: :file %>
              <div class="btn-links link-registration">
                <%= f.submit "Create Boat", class: "submit-btn custom-submit-btn" %>
                <%= link_to "Home", root_path %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/boats/show.html.erb
<main class="container text-center mt-3">
  <h1><%= @boat.name %></h1>
</div>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="card border-0 shadow-none w-100 p-0 mt-2">
        <div class="rounded-img">
          <% if @boat.photo.attached? %>
            <%= cl_image_tag @boat.photo.key, fetch_format: 'auto', transformation: { width: 750, height: 450, crop: :scale }, class: "img-fluid boat-image" %>
          <% else %>
            <p>No photo available</p>
          <% end %>
        </div>
        <div class="card-body">
          <p class="card-title"><%= @boat.name %></p>
            <div class="d-flex justify-content-between align-items-center">
              <p class="card-text"><%= @boat.location %></p>
              <p class="card-text price-text">$<%= @boat.price.to_i %>/day</p>
            </div>
        </div>
      </div>
    </div>
  </div>
 <div class="d-flex justify-content-center gap-4">
  <% if policy(@boat).destroy? %>
  <%= button_to "Delete this boat", boat_path(@boat), method: :delete, data: { confirm: "Are you sure you want to delete this boat?" }, class: "show-btn" %>
  <% end %>

  <% if policy(@boat).edit? %>
  <%= link_to "Edit this boat", edit_boat_path(@boat), class: "show-btn" %>
  <% end %>

  <%= link_to "Book this boat", new_boat_booking_path(@boat), class: "show-btn" %>

  <%= link_to "All boats", boats_path, class: "show-btn" %>
</div>

    <% if @markers.present? %>
      <div class="col-lg-8">
        <div class="sticky-top sticky-bottom">
          <div data-controller="map" id="map" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" data-map-markers-value="<%= @markers.to_json %>" style="width: 100%" class="vh-100"></div>
        </div>
      </div>
    <% end %>
</div>
<div class="row justify-content-center">
 <div class="review-card justify-content-center p-0" style="width: 950px; height: 200px;">
  <h2 class="review-header p-3">Reviews</h2>
  <%= render partial: "reviews/index", locals: { reviews: @boat.reviews } %>
</div>
</main>